packages:
  - packages/**
  - scripts/**
  - '!**/dist/**'
  - '!**/dist-*/**'

engineStrict: true
hoistPattern: []
strictPeerDependencies: false
minimumReleaseAge: 10080
blockExoticSubdeps: true
trustPolicy: no-downgrade
